### ISSUE TITLE
Running server

### ISSUE THREAD

**Issue by DylanPiercey** [egoist/unipack#1]
Hey, I have been working on making this exact task easier myself It's refreshing to see others working on it as well!

I am curious how you are handling starting up the server (not dev server) between compilations?

**Comment by egoist** [comment]
just start the server after compile? like in https://github.com/ream/ream

**Comment by DylanPiercey** [comment]
What about on re-compilation?

**Comment by egoist** [comment]
Like this?

```js
let element

serverCompiler.plugin('done', stats => {
  element = requireBundle('/path/to/bundle')
})

app.get('*', (req, res) => {
  if (!element) return res.end('please wait for compiltation...')
  renderToString(element, (err, html) => res.send(html))
})
```

**Comment by DylanPiercey** [comment]
in mean for reloading the server after the server has compiled not the browser code.

**Comment by egoist** [comment]
this does not compile your server, it compiles your app for server and client use.

If you mean refresh the browser, it will be refreshed since client compiler is triggered too.

**Comment by DylanPiercey** [comment]
Doesn't this handle building the server side? I'm thinking if I'm building an API and it's updated how is that handled/reloaded on the server side? Like nodemon or similar. Maybe that's out of scope for this library.

**Comment by egoist** [comment]
maybe something like https://github.com/palmerhq/backpack

**Comment by DylanPiercey** [comment]
I'll check that out. Thanks for chatting.
